### ISSUE TITLE
WIP

### ISSUE THREAD

**Issue by BenCos17** [BenCos17/pico-assistant#1]
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 132, in <module>
  File "<stdin>", line 48, in changeArea
  File "<stdin>", line 78, in refreshArea
  File "<stdin>", line 86, in refreshDevices
  File "api.py", line 59, in getDevices
  File "urequests.py", line 33, in json
MemoryError: memory allocation failed, allocating 296 bytes

**Comment by BenCos17** [comment]
fixed
